---
title: "Extension: Causal Effect of Intergroup Contact on Exclusionary Attitudes"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(lme4)
library(broom)
library(RColorBrewer)
library(kableExtra)
library(extrafont)
```

\begin{flushright}
Gabe Walker

February 27, 2018
\end{flushright}

```{r data, echo = FALSE, message = FALSE, error = FALSE, warning = FALSE}
### This section reads in and cleans the primary results data.

# Read in the full data and clean the names.
df <- read_csv("pnas_data.csv") %>% 
  clean_names() %>% 

# Drop unnecessary variables.
  select(-x1, -introcommu_x, -introcommu_y, -poli_id_x, -poli_id_y, -intoviews_x, -intoviews_y, -community_x, -community_y,
         -welcome_y, -disclosure_y, -best_memor, -poli_id_y, -poli_id_x, -self_i_dintr, -a_time, -obama_voter_x,
         -obama_voter_y, -romney_voter_x, -romney_voter_y) %>% 

# Create outcome variables for "number of immigrants increased,"
# "Children of undocumented be allowed to stay?", and "English as official language?".
# A positive difference term means that the individual answered more conservatively
# on the second survey.
  mutate(dif_num = numberim_y - numberim_x,
         dif_remain = remain_y - remain_x,
         dif_english = englishlan_y - englishlan_x) %>% 

# Change time_treatment to a better-looking factor.
  mutate(time_treatment = case_when(
    time_treatment == "a" ~ "Three-day treatment",
    time_treatment == "b" ~ "Ten-day treatment"
  )) %>% 

# Create a binary outcome variable if overall the individual
# was more conservative after.
  mutate(dif = case_when(
    dif_num + dif_remain + dif_english > 0 ~ 1,
    TRUE ~ 0)
    ) %>% 

# Filter out the individuals without survey results.
  filter(! is.na(dif_english)) %>% 
  filter(! is.na(dif_remain)) %>% 
  filter(! is.na(dif_num))
```

```{r models, echo = FALSE, message = FALSE, error = FALSE}
### This section makes logistic and lme models.

# Logistic regressions for the effect of treatment on the overall binary
# change in preferences.
# Treatment alone.
m1 <- glm(dif ~ treatment, df, family = binomial)
# Treatment plus separated 3- and 10-day treatments.
m2 <- glm(dif ~ treatment + time_treatment, df, family = binomial)
# m2 plus line fixed effect.
m3 <- glm(dif ~ treatment + time_treatment + line_y, df, family = binomial)
# m3 plus various demographic dimensions.
m4 <- glm(dif ~ treatment + time_treatment + line_y + obama_voter + romney_voter + male + ride_everyday + college, df, family = binomial)

# Logistic mixed-effect models.
# Treatment plus train car random effects.
m5 <- lmer(dif ~ treatment + (1 | treated_unit), df)
# m5 plus time fixed effects.
m6 <- lmer(dif ~ treatment + time_treatment + (1 | treated_unit), df)
# m6 but using treatment as a fixed factor within random units (varying slopes).
m7 <- lmer(dif ~ treatment + time_treatment + (treatment | treated_unit), df)
# m7 but using treatment as a fixed factor within random units (varying slopes and intercept).
m8 <- lmer(dif ~ treatment + time_treatment + (1 + treatment | treated_unit), df)

# Make predicted values for each of the models.
m4_pred <- m4 %>% 
  augment(type.predict = "response")
m5_pred <- m5 %>% 
  augment(type.predict = "response")
m6_pred <- m6 %>% 
  augment(type.predict = "response")
m7_pred <- m7 %>% 
  augment(type.predict = "response")
m8_pred <- m8 %>% 
  augment(type.predict = "response")
```

```{r table, echo = FALSE, message = FALSE, error = FALSE}
m5_fx <- fixef(m5)
m5_rn <- ranef(m5)
m8_fx <- fixef(m8)
m8_rn <- ranef(m8)

# Make a kable to print some of the model results.
tibble(Model = c("Treatment w/ FEs for group, line, and demographics",
                     "Treatment w/ train car random effects",
                     "Treatment w/ varying treatment effects within train cars"),
           Intercepts = c(m4$coefficients[1], m5_fx[1], m8_fx[1]),
           Treatment = c(m4$coefficients[2],  m5_fx[2], m8_fx[2])) %>% 
  kable(format = "latex", caption = "Logistic regressions of treatment on conservative shift with fixed and mixed effects") %>% 
  kable_styling(full_width = FALSE)
```

```{r chart, echo = FALSE, message = FALSE, error = FALSE}
# Choose some colors.
c <- brewer.pal(5, "Dark2")

# Plot a few of the predicted values from the models.
ggplot(df, aes(treatment, dif)) + 
  geom_jitter(width = 0, height = 0.05, alpha = 0.5) +
  geom_line(data = m4_pred, aes(treatment, .fitted), col = c[1]) +
  geom_line(data = m5_pred, aes(treatment, .fitted), col = c[2]) +
  geom_line(data = m6_pred, aes(treatment, .fitted), col = c[3]) +
  geom_line(data = m7_pred, aes(treatment, .fitted), col = c[4]) +
  geom_line(data = m8_pred, aes(treatment, .fitted), col = c[5]) +
  facet_wrap(~time_treatment) +
  labs(y = "Conservative shift", x = "Treatment") +
  theme(text=element_text(family = "LM Roman 10"), panel.background = element_blank())

```

